// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BeEllipsis: typeof import('./src/components/common-components/ellipsis/src/be-ellipsis.vue')['default']
    BePagination: typeof import('./src/components/common-components/pagination/be-pagination.vue')['default']
    BeSvgIcon: typeof import('./src/components/common-components/svg-icon/be-svg-icon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EllipsisCopy: typeof import('./src/components/common-components/ellipsis-copy/ellipsis-copy.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MsgDialog: typeof import('./src/components/common-components/msg-dialog/msg-dialog.vue')['default']
    TsgzFooter: typeof import('./src/components/tsgz-footer.vue')['default']
    TsgzNavMenu: typeof import('./src/components/tsgz-nav-menu.vue')['default']
  }
}

export { }
